# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSmokeTestSuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_adminPage(self):
    self.driver.get("https://lisbet-dokcom.github.io/cse270-teton/admin.html")
    self.driver.set_window_size(815, 854)
    elements = self.driver.find_elements(By.ID, "username")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "username").send_keys("admin")
    self.driver.find_element(By.ID, "password").send_keys("123456")
    self.driver.find_element(By.CSS_SELECTOR, ".mysubmit:nth-child(4)").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".errorMessage")
    assert len(elements) > 0
  
  def test_directoryPage(self):
    self.driver.get("https://lisbet-dokcom.github.io/cse270-teton/directory.html")
    self.driver.set_window_size(819, 854)
    self.driver.find_element(By.ID, "directory-grid").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".gold-member:nth-child(9)")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "directory-list").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)")
    assert len(elements) > 0
  
  def test_homePage1(self):
    self.driver.get("https://lisbet-dokcom.github.io/cse270-teton/index.html")
    self.driver.set_window_size(823, 854)
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".header-logo img")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".header-title > h1")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".header-title > h2")
    assert len(elements) > 0
    assert self.driver.title == "Teton Idaho CoC"
  
  def test_homePage2(self):
    self.driver.get("https://lisbet-dokcom.github.io/cse270-teton/index.html")
    self.driver.set_window_size(1588, 867)
    elements = self.driver.find_elements(By.CSS_SELECTOR, "nav")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".spotlight1 > .centered-image")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".spotlight2 > .centered-image")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.LINK_TEXT, "Join Us!")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "Join Us!").click()
    elements = self.driver.find_elements(By.LINK_TEXT, "Join")
    assert len(elements) > 0
  
  def test_joinPage(self):
    self.driver.get("https://lisbet-dokcom.github.io/cse270-teton/join.html")
    self.driver.set_window_size(811, 854)
    elements = self.driver.find_elements(By.NAME, "fname")
    assert len(elements) > 0
    self.driver.find_element(By.NAME, "fname").click()
    self.driver.find_element(By.NAME, "fname").send_keys("Elizabeth")
    self.driver.find_element(By.NAME, "lname").send_keys("Okon")
    self.driver.find_element(By.NAME, "bizname").send_keys("Lisbet")
    self.driver.find_element(By.NAME, "biztitle").send_keys("Miss")
    self.driver.find_element(By.NAME, "submit").click()
    elements = self.driver.find_elements(By.NAME, "email")
    assert len(elements) > 0
  
